# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

project 'SwitcherKitDemo.xcodeproj'

def install_pods
    pod 'SwitcherKit', :path => '../SwitcherKit.podspec'
end

target 'SwitcherKitDemo' do
    install_pods
end
